/*
 * A series of tests on transformation of serial and IDENTITY columns to the
 * Snowflake-default ones.
 */

SET snowflake.node = 1;

CREATE EXTENSION snowflake;

-- Need to check two types of serial values: DEFAULT and IDENTITY
CREATE TABLE t1(x serial);
CREATE TABLE t2 (x integer GENERATED ALWAYS AS IDENTITY);
CREATE TABLE t3 (x integer GENERATED BY DEFAULT AS IDENTITY);
CREATE SEQUENCE seq_1 START 42;

SELECT snowflake.convert_sequence_to_snowflake('t1'); -- ERROR, not a sequence
SELECT snowflake.convert_sequence_to_snowflake('seq_1'); -- ERROR, not assocoated with any relation

-- Cleanup
DROP TABLE t1,t2 CASCADE;
DROP EXTENSION snowflake;
